import os
import tempfile
from docxtpl import DocxTemplate

def generate_resume_docx(resume_data: dict, template_filename: str = "master_template.docx") -> str:
    """
    Takes the structured data generated by LangGraph and injects it into 
    the Jinja-tagged Word template. Returns the temporary file path to the generated document.
    """
    print("--- GENERATING FINAL DOCX FILE ---")
    
    # Ensure the template exists in your root directory
    if not os.path.exists(template_filename):
        raise FileNotFoundError(f"Template '{template_filename}' not found.")
        
    try:
        # 1. Load the Word template
        doc = DocxTemplate(template_filename)
        
        # 2. Inject the LangGraph dictionary directly into the template tags
        doc.render(resume_data)
        
        # 3. Create a safe, temporary file for the output
        temp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".docx")
        output_path = temp_file.name
        temp_file.close() # Close it so docxtpl can safely write to it
        
        # 4. Save the populated template
        doc.save(output_path)
        print(f"Success! Resume generated at: {output_path}")
        
        return output_path
        
    except Exception as e:
        print(f"Error generating document: {e}")
        raise e